// frontend/src/components/CartDrawer.vue
<script setup lang="ts">
import { useCartStore } from "@/stores/cart"
import { useRouter } from "vue-router"

const cart = useCartStore()
const router = useRouter()

function goToProduct(id: string) {
  router.push(`/product/${id}`)
  cart.closeCart()
}

function goToCheckout() {
  cart.closeCart()
  router.push("/checkout")
}
</script>

<template>
  <!-- Overlay -->
  <div
    v-if="cart.isOpen"
    class="overlay"
    @click="cart.closeCart"
  ></div>

  <!-- Drawer -->
  <aside :class="['drawer', cart.isOpen ? 'open' : '']">
    <div class="header">
      <h2>Cart</h2>
      <button @click="cart.closeCart">✕</button>
    </div>

    <div v-if="cart.items.length === 0" class="empty">
      <div class="empty-content">
        <div class="empty-icon">🛒</div>
        <h3>Your cart is empty</h3>
        <p>Add some art to begin your collection.</p>
      </div>
    </div>

    <div v-else class="items">
      <div
        v-for="item in cart.items"
        :key="item.product.id"
        class="item"
      >
        <!-- Imagen clickeable -->
        <img
          :src="item.product.image"
          :alt="item.product.name"
          class="clickable"
          @click="goToProduct(item.product.id)"
        />

        <div class="info">
          <!-- Nombre clickeable -->
          <p
            class="name clickable"
            @click="goToProduct(item.product.id)"
          >
            {{ item.product.name }}
          </p>

          <div class="quantity-controls">
            <button @click="cart.decreaseQuantity(item.product.id)">
              −
            </button>
            <span>{{ item.quantity }}</span>
            <button @click="cart.addToCart(item.product, 1)">
              +
            </button>
          </div>

          <p class="price">
            {{ item.product.price * item.quantity }} €
          </p>

          <button
            class="remove"
            @click="cart.removeFromCart(item.product.id)"
          >
            Remove
          </button>
        </div>
      </div>
    </div>

    <div class="footer" v-if="cart.items.length > 0">
      <p>Total: {{ cart.totalPrice }} €</p>
        <button class="btn-primary" @click="goToCheckout">
          Checkout
      </button>
    </div>
  </aside>
</template>

<style scoped>
.overlay {
  position: fixed;
  inset: 0;
  background: rgba(0,0,0,0.3);
  backdrop-filter: blur(4px);
  z-index: 9998;
}

.drawer {
  position: fixed;
  top: 0;
  right: 0;
  width: 420px;
  height: 100vh;
  background: var(--bg);
  color: var(--text);
  box-shadow: -10px 0 30px rgba(0,0,0,0.1);
  transform: translateX(100%);
  transition: transform 0.4s cubic-bezier(0.22, 1, 0.36, 1);
  z-index: 9999;
  display: flex;
  flex-direction: column;
}

.drawer.open {
  transform: translateX(0);
}

.header {
  display: flex;
  justify-content: space-between;
  padding: 1.5rem;
  border-bottom: 1px solid var(--surface);
}

.items {
  flex: 1;
  padding: 1.5rem;
  overflow-y: auto;
}

.item {
  display: flex;
  gap: 1rem;
  margin-bottom: 2rem;
}

.item img {
  width: 70px;
  height: 90px;
  object-fit: cover;
  border-radius: 8px;
  transition: transform 0.3s ease;
}

.clickable {
  cursor: pointer;
}

.clickable:hover {
  opacity: 0.8;
}

.info {
  flex: 1;
}

.name {
  font-weight: 500;
}

.quantity-controls {
  display: flex;
  align-items: center;
  gap: 0.6rem;
  margin: 0.5rem 0;
}

.quantity-controls button {
  width: 28px;
  height: 28px;
  border: 1px solid var(--surface);
  background: none;
  cursor: pointer;
}

.price {
  font-weight: 500;
  margin: 0.3rem 0;
}

.remove {
  font-size: 0.8rem;
  color: #888;
  background: none;
  border: none;
  cursor: pointer;
}

.footer {
  padding: 1.5rem;
  border-top: 1px solid var(--surface);
}

.empty {
  flex: 1;
  display: flex;
  justify-content: center;
  align-items: center;
  text-align: center;
  padding: 2rem;
}

.empty-content {
  opacity: 0.8;
}

.empty-icon {
  font-size: 2rem;
  margin-bottom: 1rem;
}

/* ========================= */
/* RESPONSIVE                */
/* ========================= */

@media (max-width: 640px) {
  .drawer {
    width: 100vw;
  }

  .header {
    padding: 1rem;
  }

  .header button {
    min-width: 44px;
    min-height: 44px;
    font-size: 1.1rem;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .items {
    padding: 1rem;
  }

  .item img {
    width: 60px;
    height: 78px;
  }

  .quantity-controls button {
    width: 36px;
    height: 36px;
    font-size: 1rem;
  }

  .footer {
    padding: 1rem;
  }

  .footer .btn-primary {
    width: 100%;
    min-height: 44px;
  }
}
</style>

// frontend-react/src/components/CartDrawer.jsx
import { useNavigate } from 'react-router-dom'
import { useCart } from '../context/CartContext'
import './CartDrawer.css'

export default function CartDrawer() {
  const cart = useCart()
  const navigate = useNavigate()

  function goToProduct(id) {
    navigate(`/product/${id}`)
    cart.closeCart()
  }

  function goToCheckout() {
    cart.closeCart()
    navigate('/checkout')
  }

  return (
    <>
      {cart.isOpen && (
        <div className="overlay" onClick={cart.closeCart}></div>
      )}

      <aside className={`drawer ${cart.isOpen ? 'open' : ''}`}>
        <div className="drawer-header">
          <h2>Cart</h2>
          <button onClick={cart.closeCart}>✕</button>
        </div>

        {cart.items.length === 0 ? (
          <div className="empty">
            <div className="empty-content">
              <div className="empty-icon">🛒</div>
              <h3>Your cart is empty</h3>
              <p>Add some art to begin your collection.</p>
            </div>
          </div>
        ) : (
          <div className="items">
            {cart.items.map(item => (
              <div key={item.product.id} className="item">
                <img
                  src={item.product.image}
                  alt={item.product.name}
                  className="clickable"
                  onClick={() => goToProduct(item.product.id)}
                />
                <div className="info">
                  <p
                    className="name clickable"
                    onClick={() => goToProduct(item.product.id)}
                  >
                    {item.product.name}
                  </p>
                  <div className="quantity-controls">
                    <button onClick={() => cart.decreaseQuantity(item.product.id)}>−</button>
                    <span>{item.quantity}</span>
                    <button onClick={() => cart.addToCart(item.product, 1)}>+</button>
                  </div>
                  <p className="price">{item.product.price * item.quantity} €</p>
                  <button className="remove" onClick={() => cart.removeFromCart(item.product.id)}>
                    Remove
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {cart.items.length > 0 && (
          <div className="drawer-footer">
            <p>Total: {cart.totalPrice} €</p>
            <button className="btn-primary" onClick={goToCheckout}>
              Checkout
            </button>
          </div>
        )}
      </aside>
    </>
  )
}
