// frontend-react/src/layouts/MainLayout.jsx
import { Outlet } from 'react-router-dom'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import CartDrawer from '../components/CartDrawer'
import { useTheme } from '../context/ThemeContext'
import './MainLayout.css'

export default function MainLayout() {
  const { dark } = useTheme()

  return (
    <div className={`layout ${dark ? 'dark' : 'light'}`}>
      <Navbar />
      <main>
        <Outlet />
      </main>
      <CartDrawer />
      <Footer />
    </div>
  )
}

// frontend/src/layouts/MainLayout.vue
<script setup lang="ts">
import { useThemeStore } from "@/stores/theme"
import CartDrawer from "@/components/CartDrawer.vue"
import Footer from "@/components/Footer.vue"
import Navbar from "@/components/Navbar.vue"
import "@/assets/styles/theme.css"
import "@/assets/styles/ui.css"

const theme = useThemeStore()
</script>

<template>
  <div :class="['layout', theme.dark ? 'dark' : 'light']">

    <Navbar />

    <main>
      <RouterView />
    </main>

    <CartDrawer />
    <Footer />

  </div>
</template>

<style scoped>
.layout {
  background: var(--bg);
  color: var(--text);
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  transition: background 0.3s ease, color 0.3s ease;
}

main {
  flex: 1;
}
</style>
